// Queen Mode Phrases - BadAss Personality
// First-person female perspective with sarcastic black humor

export const queenPhrases = {
  menstrual: {
    name: 'Bloody Hell Week',
    description: 'F*ck this sh*t. Where\'s the chocolate?',
    calendarTooltip: 'The Red Wedding - Approach with caution',
    moods: [
      "I'm basically a crime scene down there",
      "Currently accepting applications for a new uterus",
      "My cramps have cramps",
      "I've eaten everything in a 5-mile radius",
      "Currently identifying as a heating pad",
      "Bloated like a dead whale on a beach",
      "Considering violence as a valid life choice",
      "My back hurts, my boobs hurt, existence hurts",
      "I sneezed and created a horror movie scene",
      "Currently powered by rage and chocolate",
      "If looks could kill, I'd be a serial killer",
      "Everything is stupid and I hate it all",
      "I'm not crying, my eyes are just bleeding too",
      "My uterus is having a temper tantrum",
      "Currently accepting donations of new organs",
      "I've transcended pain and entered a new dimension",
      "Wearing my murder pants today",
      "My hormones are having a rave without me",
      "I'm one inconvenience away from arson",
      "Currently experiencing all emotions simultaneously",
      "My body is a betrayal factory",
      "I'm basically a shark attack victim who survived",
      "Existing is overrated anyway",
      "My pain scale goes to 11 today",
      "I've eaten my body weight in carbs",
      "Currently accepting prayers and chocolate",
      "My uterus is doing its best Alien impression",
      "I'm too tired to be tired",
      "Everything hurts and I'm dying",
      "Currently unavailable due to internal renovation",
      "My body hates me and the feeling is mutual",
      "I'm a delicate f*cking flower, okay?"
    ],
    cravings: [
      { icon: 'Cookie', text: "entire chocolate factory" },
      { icon: 'IceCream', text: "Ben & Jerry's, all flavors" },
      { icon: 'Candy', text: "anything with sugar" },
      { icon: 'Soup', text: "molten lava cake" },
      { icon: 'Coffee', text: "wine, lots of wine" },
      { icon: 'Wheat', text: "entire loaf of bread" },
      { icon: 'Cherry', text: "chocolate-covered everything" },
      { icon: 'Milk', text: "cheese, all the cheese" },
      { icon: 'Banana', text: "french fries dipped in ice cream" },
      { icon: 'Apple', text: "pizza with extra everything" },
      { icon: 'Fish', text: "sushi boat for one" },
      { icon: 'Salad', text: "salad... just kidding, cake" },
      { icon: 'Egg', text: "breakfast for every meal" },
      { icon: 'Nut', text: "Nutella by the spoonful" },
      { icon: 'Carrot', text: "carrot cake counts as vegetables" },
      { icon: 'Cookie', text: "cookie dough, raw" },
      { icon: 'IceCream', text: "milkshake IV drip" },
      { icon: 'Candy', text: "Halloween candy stash" },
      { icon: 'Soup', text: "mac and cheese swimming pool" },
      { icon: 'Coffee', text: "coffee with a side of coffee" },
      { icon: 'Wheat', text: "pasta mountain" },
      { icon: 'Cherry', text: "pie, whole pie" },
      { icon: 'Milk', text: "chocolate milk river" },
      { icon: 'Banana', text: "banana split for breakfast" },
      { icon: 'Apple', text: "caramel apples, dozen" },
      { icon: 'Fish', text: "fish and chips and chips" },
      { icon: 'Salad', text: "Caesar salad, hold the salad" },
      { icon: 'Egg', text: "eggs Benedict on everything" },
      { icon: 'Nut', text: "peanut butter from the jar" },
      { icon: 'Carrot', text: "carbs, just carbs" },
      { icon: 'Cookie', text: "grandma's cookie jar" },
      { icon: 'IceCream', text: "ice cream for dinner" }
    ]
  },
  follicular: {
    name: 'Finally Got My Sh*t Together',
    description: 'Look at me being a functional human being!',
    calendarTooltip: 'She\'s back to normal-ish',
    moods: [
      "I'm practically a Disney princess today",
      "My skin is glowing and I'm not dying",
      "Suddenly I remember why I like being alive",
      "I cleaned something without crying",
      "I can see my ankles again!",
      "My jeans fit and I'm not homicidal",
      "I actually want to leave the house",
      "Look at me adulting like a boss",
      "I remembered to shower AND use soap",
      "My brain works again, it's a miracle",
      "I can form complete sentences!",
      "Productivity level: Actually doing sh*t",
      "I don't hate everyone today",
      "My body and I are on speaking terms",
      "I exercised and didn't die",
      "Someone complimented me and I didn't cry",
      "I'm basically Wonder Woman right now",
      "My hormones are actually cooperating",
      "I made a plan and stuck to it",
      "Energy level: Could fight a bear",
      "I put on real pants today",
      "My mood is so stable it's suspicious",
      "I'm organized AF right now",
      "Look at me having rational thoughts",
      "I can handle minor inconveniences",
      "My skin cleared up, my crops are thriving",
      "I'm feeling cute, might delete later",
      "Confidence level: Could rule a small country",
      "I actually like people today",
      "My life is somewhat together",
      "I remembered all my passwords",
      "I'm basically unstoppable right now"
    ],
    cravings: [
      { icon: 'Salad', text: "actual vegetables, wtf" },
      { icon: 'Apple', text: "fruit that isn't covered in chocolate" },
      { icon: 'Fish', text: "salmon and quinoa like a health goddess" },
      { icon: 'Carrot', text: "smoothie bowl aesthetic" },
      { icon: 'Egg', text: "protein-packed breakfast" },
      { icon: 'Wheat', text: "whole grain everything" },
      { icon: 'Nut', text: "almonds and self-control" },
      { icon: 'Milk', text: "Greek yogurt parfait" },
      { icon: 'Cherry', text: "fresh berries, fancy" },
      { icon: 'Banana', text: "banana for actual potassium" },
      { icon: 'Coffee', text: "green tea, I'm sophisticated" },
      { icon: 'Soup', text: "bone broth, so trendy" },
      { icon: 'Cookie', text: "energy balls, not cookies" },
      { icon: 'IceCream', text: "frozen yogurt, I'm being good" },
      { icon: 'Candy', text: "dark chocolate, it's healthy right?" },
      { icon: 'Salad', text: "kale salad unironically" },
      { icon: 'Apple', text: "apple with almond butter" },
      { icon: 'Fish', text: "poke bowl perfection" },
      { icon: 'Carrot', text: "veggie sticks and hummus" },
      { icon: 'Egg', text: "avocado toast, basic but good" },
      { icon: 'Wheat', text: "overnight oats aesthetic" },
      { icon: 'Nut', text: "trail mix, I'm outdoorsy now" },
      { icon: 'Milk', text: "matcha latte vibes" },
      { icon: 'Cherry', text: "acai bowl for the gram" },
      { icon: 'Banana', text: "nice cream, not ice cream" },
      { icon: 'Coffee', text: "kombucha, I'm that person now" },
      { icon: 'Soup', text: "miso soup, so zen" },
      { icon: 'Cookie', text: "rice cakes... and I like them?" },
      { icon: 'IceCream', text: "chia pudding pretending to be dessert" },
      { icon: 'Candy', text: "dates stuffed with almonds" },
      { icon: 'Salad', text: "Buddha bowl bliss" },
      { icon: 'Apple', text: "green juice, look at me go" }
    ]
  },
  ovulation: {
    name: 'Horny AF',
    description: 'Is it hot in here or is it just my hormones?',
    calendarTooltip: 'Baby-making factory is OPEN',
    moods: [
      "Everything is sexy, even this lamp",
      "My ovaries are doing the cha-cha",
      "I'd climb that like a tree",
      "Suddenly everyone looks attractive",
      "My body is ready... for EVERYTHING",
      "Fertility goddess mode: ACTIVATED",
      "I could seduce a statue right now",
      "My pheromones have pheromones",
      "Currently accepting applications for baby daddy",
      "I'm basically in heat",
      "My biological clock is SCREAMING",
      "Everything reminds me of... you know",
      "I'm one wine glass away from bad decisions",
      "My standards have temporarily left the building",
      "Feeling myself a little TOO much",
      "I could make a nun reconsider",
      "My eggs are doing a sales pitch",
      "Ovulation station, all aboard!",
      "My hormones are writing checks my body can't cash",
      "I'm a walking fertility advertisement",
      "Currently radiating big reproductive energy",
      "My ovaries just sent a mass text",
      "Peak baby-making mode engaged",
      "I'm basically a human magnet right now",
      "My body is open for business",
      "Evolution wants me to make terrible choices",
      "I'm one compliment away from pregnancy",
      "My eggs are having a going-out-of-business sale",
      "Fertility level: Extremely inconvenient",
      "I could get pregnant from a handshake",
      "My hormones are in the driver's seat",
      "Currently accepting breeding applications"
    ],
    cravings: [
      { icon: 'Cherry', text: "oysters, wink wink" },
      { icon: 'Banana', text: "bananas... for the potassium" },
      { icon: 'Fish', text: "sushi date vibes" },
      { icon: 'Coffee', text: "espresso martini energy" },
      { icon: 'Candy', text: "chocolate-covered strawberries" },
      { icon: 'Apple', text: "forbidden fruit" },
      { icon: 'Milk', text: "whipped cream situations" },
      { icon: 'Nut', text: "nuts... make your own joke" },
      { icon: 'IceCream', text: "something to cool me down" },
      { icon: 'Soup', text: "hot and steamy anything" },
      { icon: 'Cookie', text: "fortune cookies with spicy fortunes" },
      { icon: 'Wheat', text: "carbs for... energy" },
      { icon: 'Egg', text: "eggs, how ironic" },
      { icon: 'Salad', text: "cucumber... salad" },
      { icon: 'Carrot', text: "phallic vegetables" },
      { icon: 'Cherry', text: "cherries, obviously" },
      { icon: 'Banana', text: "banana split, emphasis on split" },
      { icon: 'Fish', text: "raw bar experience" },
      { icon: 'Coffee', text: "Irish coffee, liquid courage" },
      { icon: 'Candy', text: "anything I can lick" },
      { icon: 'Apple', text: "honey crisp apples, emphasis on honey" },
      { icon: 'Milk', text: "milkshake to bring boys to yard" },
      { icon: 'Nut', text: "mixed nuts, I'm not picky" },
      { icon: 'IceCream', text: "ice cream cone, slowly" },
      { icon: 'Soup', text: "spicy ramen to match my mood" },
      { icon: 'Cookie', text: "gingerbread men, anatomically correct" },
      { icon: 'Wheat', text: "baguette, French style" },
      { icon: 'Egg', text: "deviled eggs, emphasis on devil" },
      { icon: 'Salad', text: "tossed salad jokes write themselves" },
      { icon: 'Carrot', text: "baby carrots, or full size" },
      { icon: 'Cherry', text: "anything involving popping" },
      { icon: 'Banana', text: "frozen banana, for reasons" }
    ]
  },
  luteal: {
    name: 'Getting Real Tired of This BS',
    description: 'Starting to question my life choices...',
    calendarTooltip: 'Patience wearing thin',
    moods: [
      "My patience has left the building",
      "Everything is annoying and I'm over it",
      "I'm not mad, I'm just disappointed in everyone",
      "My tolerance is at an all-time low",
      "I've started 10 arguments in my head",
      "Everyone is wrong except me",
      "I'm too tired to pretend to care",
      "My give-a-f*ck is broken",
      "Currently accepting applications for a new life",
      "I'm not antisocial, everyone just sucks",
      "My bra is trying to kill me",
      "Everything is stupid, especially this",
      "I've perfected the resting bitch face",
      "Don't talk to me until... never",
      "My energy left with my patience",
      "I'm one comment away from going feral",
      "Currently identifying as a grumpy cat",
      "Everything hurts and nothing matters",
      "My enthusiasm has flatlined",
      "I'm basically a walking eye roll",
      "Sarcasm level: Maximum capacity",
      "I've run out of f*cks to give",
      "My spirit animal is a sloth",
      "I'm too old for this sh*t",
      "Currently unavailable for human interaction",
      "My mood ring just turned black",
      "I'm not crying, you're crying",
      "Everything is exhausting",
      "My patience wore skinny jeans and left",
      "I'm one inconvenience from hibernation",
      "Currently accepting wine donations",
      "My body is staging a rebellion"
    ],
    cravings: [
      { icon: 'Coffee', text: "IV drip of caffeine" },
      { icon: 'Candy', text: "sugar to fuel my rage" },
      { icon: 'Wheat', text: "bread bowl full of bread" },
      { icon: 'Cheese', text: "cheese platter for one" },
      { icon: 'Cookie', text: "cookies for breakfast" },
      { icon: 'IceCream', text: "ice cream from the container" },
      { icon: 'Soup', text: "comfort food injection" },
      { icon: 'Milk', text: "hot chocolate with extra chocolate" },
      { icon: 'Nut', text: "trail mix, heavy on the chocolate" },
      { icon: 'Apple', text: "apple pie, hold the apple" },
      { icon: 'Fish', text: "fish and chips, heavy on chips" },
      { icon: 'Egg', text: "scrambled eggs with cheese mountain" },
      { icon: 'Salad', text: "salad... psyche, pizza" },
      { icon: 'Carrot', text: "carrot cake, it's a vegetable" },
      { icon: 'Cherry', text: "cherry garcia by the pint" },
      { icon: 'Coffee', text: "coffee with a coffee chaser" },
      { icon: 'Candy', text: "gummy bears army" },
      { icon: 'Wheat', text: "pasta nest I can hide in" },
      { icon: 'Cheese', text: "grilled cheese tower" },
      { icon: 'Cookie', text: "cookie sandwich with cookie filling" },
      { icon: 'IceCream', text: "sundae bar, I am the bar" },
      { icon: 'Soup', text: "soup in a bread bowl in a bigger bowl" },
      { icon: 'Milk', text: "cereal for dinner" },
      { icon: 'Nut', text: "peanut butter spoon collection" },
      { icon: 'Apple', text: "caramel apples, mostly caramel" },
      { icon: 'Fish', text: "sushi conveyor belt rental" },
      { icon: 'Egg', text: "egg mcmuffin stack" },
      { icon: 'Salad', text: "taco salad, 90% taco" },
      { icon: 'Carrot', text: "vegetables deep fried beyond recognition" },
      { icon: 'Cherry', text: "cherry pie with ice cream moat" },
      { icon: 'Coffee', text: "espresso shots like tequila shots" },
      { icon: 'Candy', text: "candy corn even though it's July" }
    ]
  },
  lateLuteal: {
    name: 'Pre-Chaos Mood Swings',
    description: 'Don\'t even look at me wrong today',
    calendarTooltip: 'Emotional rollercoaster in progress',
    moods: [
      "I'm fine. I'M FINE. WHY DOES EVERYONE KEEP ASKING?",
      "Laughing and crying simultaneously",
      "My emotions are having a battle royale",
      "I just cried at a commercial about paper towels",
      "Happy, sad, angry, repeat",
      "My mood changes faster than I can track",
      "Currently experiencing all seasons in one hour",
      "I'm a walking contradiction",
      "Everything is beautiful and terrible",
      "I love everyone but also hate them",
      "My feelings have feelings",
      "Emotional stability has left the chat",
      "I'm on an emotional rollercoaster without a seatbelt",
      "Just had 17 moods in 5 minutes",
      "I'm not bipolar, I'm multi-polar",
      "My emotions are playing musical chairs",
      "Currently feeling 73 things at once",
      "I'm fine but also falling apart",
      "My mood ring exploded",
      "Emotionally, I'm doing parkour",
      "I'm a human mood swing",
      "My feelings are in a blender",
      "I'm laughing but also want to fight",
      "Emotional whiplash is my cardio",
      "My mood GPS is recalculating",
      "I'm stable like a house of cards in a hurricane",
      "Currently buffering between emotions",
      "My feelings are having a rave",
      "I'm okay but also definitely not",
      "My emotional spectrum is a disco ball",
      "Plot twist: I don't know how I feel either",
      "I'm riding the bipolar express"
    ],
    cravings: [
      { icon: 'Candy', text: "emotional support candy" },
      { icon: 'IceCream', text: "ice cream for each feeling" },
      { icon: 'Cookie', text: "cookies to match my moods" },
      { icon: 'Coffee', text: "coffee or wine, can't decide" },
      { icon: 'Wheat', text: "pasta to fill the void" },
      { icon: 'Cheese', text: "cheese wheel to cry into" },
      { icon: 'Soup', text: "soup that understands me" },
      { icon: 'Milk', text: "chocolate milk nostalgia" },
      { icon: 'Nut', text: "mixed nuts like my emotions" },
      { icon: 'Apple', text: "apple pie like mom's hugs" },
      { icon: 'Fish', text: "sushi to feel fancy while crying" },
      { icon: 'Egg', text: "eggs, scrambled like my brain" },
      { icon: 'Salad', text: "salad but make it emotional" },
      { icon: 'Carrot', text: "baby carrots because I'm baby" },
      { icon: 'Cherry', text: "cherry everything always" },
      { icon: 'Candy', text: "sour patch kids, they get me" },
      { icon: 'IceCream', text: "neapolitan for my 3 personalities" },
      { icon: 'Cookie', text: "fortune cookies with therapy advice" },
      { icon: 'Coffee', text: "latte with extra feelings" },
      { icon: 'Wheat', text: "bagels, one for each emotion" },
      { icon: 'Cheese', text: "string cheese to play with nervously" },
      { icon: 'Soup', text: "chicken soup for my dramatic soul" },
      { icon: 'Milk', text: "strawberry milk for inner child" },
      { icon: 'Nut', text: "cashews because I'm nuts" },
      { icon: 'Apple', text: "apple juice box therapy" },
      { icon: 'Fish', text: "goldfish crackers, the smiling kind" },
      { icon: 'Egg', text: "egg drop soup for comfort" },
      { icon: 'Salad', text: "word salad matches my thoughts" },
      { icon: 'Carrot', text: "carrot sticks for stress eating" },
      { icon: 'Cherry', text: "maraschino cherries, artificial like my stability" },
      { icon: 'Coffee', text: "decaf?? Who am I kidding" },
      { icon: 'Candy', text: "mood ring pops" }
    ]
  },
  premenstrual: {
    name: 'Apocalypse Countdown',
    description: 'If you value your life, bring snacks',
    calendarTooltip: 'DEFCON 1 - Maximum alert',
    moods: [
      "The end is near and I'm the harbinger",
      "My uterus is preparing for war",
      "I can feel the storm coming",
      "Currently accepting bribes in chocolate form",
      "T-minus 2 days to total destruction",
      "My body is a ticking time bomb",
      "I'm basically a hurricane warning",
      "The calm before the shitstorm",
      "My hormones are loading the cannons",
      "I'm a walking biohazard sign",
      "Countdown to chaos initiated",
      "My ovaries are writing their will",
      "I'm experiencing pre-traumatic stress",
      "The four horsemen are my cramps",
      "My uterus filed for divorce",
      "I'm a natural disaster waiting to happen",
      "Currently in the eye of the hormone hurricane",
      "My body is sending evacuation notices",
      "I can smell blood... and it's mine",
      "The prophecy is about to be fulfilled",
      "My internal organs are having a mutiny",
      "I'm basically a werewolf at this point",
      "The red wedding is being planned",
      "My body is preparing for the purge",
      "I'm a volcano about to erupt",
      "Currently experiencing the end times",
      "My hormones are playing the final boss music",
      "I'm the trailer for next week's horror show",
      "Tsunami warning: It's coming",
      "My uterus is sharpening its knives",
      "I'm patient zero of the hormone apocalypse",
      "Winter is coming and it's made of blood"
    ],
    cravings: [
      { icon: 'Cookie', text: "all the cookies in existence" },
      { icon: 'IceCream', text: "ice cream truck hijacking" },
      { icon: 'Candy', text: "Halloween candy in July" },
      { icon: 'Wheat', text: "bread fortress to hide in" },
      { icon: 'Coffee', text: "wine bottle with a straw" },
      { icon: 'Cheese', text: "cheese fondue swimming pool" },
      { icon: 'Soup', text: "soup IV drip" },
      { icon: 'Milk', text: "chocolate fountain installation" },
      { icon: 'Nut', text: "nut butter by the jar" },
      { icon: 'Apple', text: "apple pie bed" },
      { icon: 'Fish', text: "sushi train robbery" },
      { icon: 'Egg', text: "omelet the size of my feelings" },
      { icon: 'Salad', text: "salad... just kidding, bring cake" },
      { icon: 'Carrot', text: "carrot cake castle" },
      { icon: 'Cherry', text: "cherry everything empire" },
      { icon: 'Cookie', text: "cookie monster's personal stash" },
      { icon: 'IceCream', text: "Ben & Jerry's stockholder portions" },
      { icon: 'Candy', text: "Willy Wonka's entire factory" },
      { icon: 'Wheat', text: "pasta pool to swim in" },
      { icon: 'Coffee', text: "coffee or alcohol, dealer's choice" },
      { icon: 'Cheese', text: "cheese wheel bed" },
      { icon: 'Soup', text: "soup in a swimming pool" },
      { icon: 'Milk', text: "milkshake waterfall" },
      { icon: 'Nut', text: "nuts about going nuts" },
      { icon: 'Apple', text: "apple orchard ownership" },
      { icon: 'Fish', text: "aquarium but it's all sushi" },
      { icon: 'Egg', text: "breakfast for every meal forever" },
      { icon: 'Salad', text: "Caesar's entire empire" },
      { icon: 'Carrot', text: "vegetables fried beyond recognition" },
      { icon: 'Cherry', text: "cherry on top of everything" },
      { icon: 'Coffee', text: "espresso machine surgically attached" },
      { icon: 'Candy', text: "sugar coma preparation kit" }
    ]
  }
};

// Helper function to get random phrase while tracking usage
export const getRandomQueenPhrase = (phase, type) => {
  const phrases = queenPhrases[phase]?.[type];
  if (!phrases || phrases.length === 0) return null;
  
  // Simple random selection for now
  // TODO: Implement proper phrase tracking to avoid repetition
  const randomIndex = Math.floor(Math.random() * phrases.length);
  return type === 'moods' 
    ? phrases[randomIndex]
    : phrases[randomIndex];
};

// Export phase names for compatibility
export const queenPhaseNames = {
  menstrual: 'Bloody Hell Week',
  follicular: 'Finally Got My Sh*t Together',
  ovulation: 'Horny AF',
  luteal: 'Getting Real Tired of This BS',
  lateLuteal: 'Pre-Chaos Mood Swings',
  premenstrual: 'Apocalypse Countdown'
};

// Export UI text specific to Queen mode
export const queenUIText = {
  modeToggleOff: 'Queen',
  testModeLabel: 'Test Mode',
  phaseLabel: 'Current Phase',
  fertilityLabel: 'Baby Factory Status',
  settingsTitle: 'Settings',
  historyTitle: 'History',
  todayButton: 'Today',
  dayLabel: 'Day',
  ofLabel: 'of',
  cycleDayLabel: 'Cycle Day'
};