// King Mode Phrases - Partner Warning System
// Third-person partner perspective with survival tips

export const kingPhrases = {
  menstrual: {
    name: 'Code Red Alert',
    description: 'Approach with chocolate. And caution.',
    calendarTooltip: 'DANGER ZONE - Bring offerings',
    moods: [
      "She's losing blood, don't make her lose her mind",
      "Currently unavailable for rational discussion",
      "Chocolate is not optional, it's survival",
      "She's in pain, you're in danger",
      "Emergency snack protocols activated",
      "Her uterus is angry, tread carefully",
      "This is not a drill, bring ice cream",
      "She needs space... and snacks",
      "Currently operating on emergency backup hormones",
      "Approach only with offerings",
      "Her patience has been temporarily discontinued",
      "Warning: Emotional range set to 'ALL'",
      "She's not mean, she's in pain",
      "Survival tip: Agree with everything",
      "Her body is staging a rebellion",
      "Code Red: Literally and figuratively",
      "She's fighting a battle you can't see",
      "Comfort level required: Maximum",
      "She needs heat packs and understanding",
      "Currently experiencing technical difficulties",
      "Her murder face is not personal",
      "Supplies needed: Chocolate, patience, more chocolate",
      "She's not dramatic, she's in pain",
      "Warning: Logic temporarily offline",
      "She's basically bleeding to death monthly",
      "Emergency protocols: Snacks and silence",
      "Her body hates her, don't join in",
      "Currently powered by pain and rage",
      "She's a warrior, treat her like one",
      "Survival mode: Just be nice",
      "Her uterus is having a tantrum",
      "Approach rating: Extremely hazardous"
    ],
    cravings: [
      { icon: 'Cookie', text: "emergency cookie delivery" },
      { icon: 'IceCream', text: "ice cream peace offering" },
      { icon: 'Candy', text: "chocolate survival kit" },
      { icon: 'Soup', text: "comfort food parade" },
      { icon: 'Coffee', text: "whatever she wants drink" },
      { icon: 'Wheat', text: "carb mountain delivery" },
      { icon: 'Cherry', text: "dessert first policy" },
      { icon: 'Milk', text: "cheese board distraction" },
      { icon: 'Banana', text: "banana bread bribery" },
      { icon: 'Apple', text: "apple pie peace treaty" },
      { icon: 'Fish', text: "sushi silence bribe" },
      { icon: 'Salad', text: "salad? Are you insane?" },
      { icon: 'Egg', text: "breakfast in bed mandatory" },
      { icon: 'Nut', text: "nut butter emergency jar" },
      { icon: 'Carrot', text: "cake disguised as vegetables" },
      { icon: 'Cookie', text: "cookie ammunition" },
      { icon: 'IceCream', text: "ice cream diplomacy" },
      { icon: 'Candy', text: "candy peacekeeping force" },
      { icon: 'Soup', text: "soup for her soul" },
      { icon: 'Coffee', text: "coffee on demand" },
      { icon: 'Wheat', text: "bread fortress supplies" },
      { icon: 'Cherry', text: "cherry on top everything" },
      { icon: 'Milk', text: "dairy delivery service" },
      { icon: 'Banana', text: "banana split negotiations" },
      { icon: 'Apple', text: "apple turnover truce" },
      { icon: 'Fish', text: "fish and silence combo" },
      { icon: 'Salad', text: "pizza disguised as salad" },
      { icon: 'Egg', text: "egg-cellent distraction" },
      { icon: 'Nut', text: "nuts for her sanity" },
      { icon: 'Carrot', text: "carrot cake camouflage" },
      { icon: 'Cookie', text: "cookie peace talks" },
      { icon: 'IceCream', text: "frozen treaty treats" }
    ]
  },
  follicular: {
    name: 'Safe Zone Active',
    description: 'She\'s back! Quick, make plans!',
    calendarTooltip: 'Safe zone - She likes you again',
    moods: [
      "She remembers why she keeps you around",
      "Currently accepting compliments and date nights",
      "Her energy is back, use it wisely",
      "She's actually listening when you talk",
      "This is your window for difficult conversations",
      "She's in a good mood, don't waste it",
      "Currently available for adventures",
      "Her patience has been restored",
      "She actually wants to do things",
      "Quick! She's feeling social!",
      "Her smile is genuine again",
      "She's not plotting your death anymore",
      "Currently open to suggestions",
      "She remembers she loves you",
      "This is peak girlfriend material time",
      "She's actually interested in your day",
      "Her energy could power the city",
      "She wants to go out! Alert the media!",
      "Currently accepting physical affection",
      "She's laughing at your jokes again",
      "Her motivation has returned from vacation",
      "She's making plans that include you",
      "Currently radiating positive energy",
      "She cleaned something voluntarily",
      "Her appetite for life is back",
      "She's singing in the shower again",
      "Currently available for couple activities",
      "She suggested date night first",
      "Her mood ring says 'happy'",
      "She's actually excited about things",
      "Currently in girlfriend of the year mode",
      "She wants to try that new restaurant"
    ],
    cravings: [
      { icon: 'Salad', text: "she wants healthy food?!" },
      { icon: 'Apple', text: "fruit without chocolate coating" },
      { icon: 'Fish', text: "fancy dinner opportunity" },
      { icon: 'Egg', text: "brunch date incoming" },
      { icon: 'Carrot', text: "she's eating vegetables willingly" },
      { icon: 'Nut', text: "healthy snacks phase" },
      { icon: 'Wheat', text: "she'll share your pizza" },
      { icon: 'Milk', text: "smoothie dates possible" },
      { icon: 'Cherry', text: "fruit for dessert works" },
      { icon: 'Banana', text: "gym partnership renewed" },
      { icon: 'Soup', text: "cooking together time" },
      { icon: 'Coffee', text: "coffee dates approved" },
      { icon: 'Salad', text: "restaurant adventures" },
      { icon: 'Apple', text: "farmers market trips" },
      { icon: 'Fish', text: "sushi date night" },
      { icon: 'Egg', text: "breakfast together goals" },
      { icon: 'Carrot', text: "healthy meal prep partner" },
      { icon: 'Nut', text: "trail mix hiking buddy" },
      { icon: 'Wheat', text: "bakery visits allowed" },
      { icon: 'Milk', text: "latte art appreciation" },
      { icon: 'Cherry', text: "picking fruit together" },
      { icon: 'Banana', text: "smoothie bowl dates" },
      { icon: 'Soup', text: "soup and conversation" },
      { icon: 'Coffee', text: "morning coffee ritual" },
      { icon: 'Salad', text: "trying new places" },
      { icon: 'Apple', text: "healthy choice support" },
      { icon: 'Fish', text: "cooking class couple" },
      { icon: 'Egg', text: "weekend brunch plans" },
      { icon: 'Carrot', text: "grocery shopping together" },
      { icon: 'Nut', text: "sharing snacks happily" },
      { icon: 'Wheat', text: "bread making adventures" },
      { icon: 'Milk', text: "cheese tasting dates" }
    ]
  },
  ovulation: {
    name: 'High Energy Warning',
    description: 'High energy alert. She\'s feeling good.',
    calendarTooltip: 'GREEN LIGHT - Safe to approach',
    moods: [
      "She's looking at you like a snack",
      "Currently accepting all applications",
      "Her hormones called, they want you",
      "This is not a drill, she's ready",
      "She's basically hunting you",
      "Currently radiating 'come hither' energy",
      "She's interested in... everything",
      "Her body has one agenda today",
      "She's giving you THE look",
      "Currently open for business",
      "She's more interested in you than Netflix",
      "Her attraction level: Maximum",
      "She actually initiated",
      "Currently in goddess mode",
      "She's wearing THAT outfit",
      "Her flirt game is strong",
      "She keeps touching you",
      "Currently broadcasting availability",
      "She suggested an early night",
      "Her pheromones are in overdrive",
      "She's laughing at ALL your jokes",
      "Currently finding you irresistible",
      "She turned off the TV",
      "Her energy is... focused",
      "She's making all the moves",
      "Currently in seduction mode",
      "She bought new lingerie",
      "Her bedroom eyes are activated",
      "She's very... affectionate",
      "Currently prioritizing couple time",
      "She keeps suggesting 'naps'",
      "Her interest level: Off the charts"
    ],
    cravings: [
      { icon: 'Cherry', text: "aphrodisiac menu planning" },
      { icon: 'Banana', text: "energy fuel required" },
      { icon: 'Fish', text: "oyster bar visit?" },
      { icon: 'Candy', text: "chocolate and champagne" },
      { icon: 'Coffee', text: "energy drinks on standby" },
      { icon: 'Nut', text: "stamina snacks needed" },
      { icon: 'Egg', text: "protein for... activities" },
      { icon: 'Milk', text: "calcium for... reasons" },
      { icon: 'Apple', text: "forbidden fruit mood" },
      { icon: 'Wheat', text: "carbo-loading required" },
      { icon: 'IceCream', text: "dessert in bed menu" },
      { icon: 'Cookie', text: "midnight snack prep" },
      { icon: 'Salad', text: "light dinners only" },
      { icon: 'Soup', text: "quick meal solutions" },
      { icon: 'Carrot', text: "vitamin boost needed" },
      { icon: 'Cherry', text: "cherry metaphors" },
      { icon: 'Banana', text: "potassium reserves" },
      { icon: 'Fish', text: "romantic dinner plans" },
      { icon: 'Candy', text: "sweet treats after" },
      { icon: 'Coffee', text: "morning after coffee" },
      { icon: 'Nut', text: "energy bar stash" },
      { icon: 'Egg', text: "breakfast in bed prep" },
      { icon: 'Milk', text: "hydration station" },
      { icon: 'Apple', text: "healthy quick bites" },
      { icon: 'Wheat', text: "easy meals planned" },
      { icon: 'IceCream', text: "celebration desserts" },
      { icon: 'Cookie', text: "sugar rush ready" },
      { icon: 'Salad', text: "keeping it light" },
      { icon: 'Soup', text: "room service backup" },
      { icon: 'Carrot', text: "energy vegetables" },
      { icon: 'Cherry', text: "romantic fruit plate" },
      { icon: 'Banana', text: "morning smoothies" }
    ]
  },
  luteal: {
    name: 'Patience Level: Low',
    description: 'Her patience is running low. Proceed carefully.',
    calendarTooltip: 'CAUTION - Tolerance levels dropping',
    moods: [
      "She's starting to find you annoying",
      "Currently running low on patience",
      "Her fake smile is getting tired",
      "She needs more space than NASA",
      "Currently questioning all life choices",
      "She's not mad, just... disappointed",
      "Her energy bill came due",
      "She's entering hibernation mode",
      "Currently unavailable for stupidity",
      "She's practicing selective hearing",
      "Her tolerance is at 25%",
      "She needs a nap and silence",
      "Currently in 'don't push it' mode",
      "She's too tired to pretend",
      "Her social battery is dying",
      "She's considering a solo vacation",
      "Currently operating on reserve power",
      "She's not ignoring you, just resting",
      "Her enthusiasm has left the building",
      "She needs Netflix, not chill",
      "Currently in energy-saving mode",
      "She's rationing her niceness",
      "Her smile muscles are tired",
      "She's choosing battles wisely",
      "Currently accepting space and snacks",
      "She's not antisocial, just selective",
      "Her 'give a damn' is broken",
      "She needs recharging time",
      "Currently on emotional battery saver",
      "She's preparing for the storm",
      "Her mood is 'meh' at best",
      "She's saving energy for survival"
    ],
    cravings: [
      { icon: 'Cookie', text: "comfort food incoming" },
      { icon: 'IceCream', text: "ice cream peace offering" },
      { icon: 'Candy', text: "chocolate first aid kit" },
      { icon: 'Soup', text: "warm comfort required" },
      { icon: 'Coffee', text: "caffeine IV needed" },
      { icon: 'Wheat', text: "carb loading phase" },
      { icon: 'Cherry', text: "dessert therapy time" },
      { icon: 'Milk', text: "cheese plate solo" },
      { icon: 'Banana', text: "banana bread comfort" },
      { icon: 'Apple', text: "baked goods only" },
      { icon: 'Fish', text: "takeout saves lives" },
      { icon: 'Salad', text: "salad? Not today" },
      { icon: 'Egg', text: "breakfast for dinner" },
      { icon: 'Nut', text: "snack stockpiling" },
      { icon: 'Carrot', text: "vegetables in cake form" },
      { icon: 'Cookie', text: "cookie emergency" },
      { icon: 'IceCream', text: "frozen feelings food" },
      { icon: 'Candy', text: "candy stash raiding" },
      { icon: 'Soup', text: "soup and solitude" },
      { icon: 'Coffee', text: "coffee dependency rising" },
      { icon: 'Wheat', text: "bread is life now" },
      { icon: 'Cherry', text: "pie fixes everything" },
      { icon: 'Milk', text: "dairy comfort zone" },
      { icon: 'Banana', text: "banana everything phase" },
      { icon: 'Apple', text: "apple crisp mood" },
      { icon: 'Fish', text: "easy dinner solutions" },
      { icon: 'Salad', text: "pizza renamed salad" },
      { icon: 'Egg', text: "simple foods only" },
      { icon: 'Nut', text: "nut butter therapy" },
      { icon: 'Carrot', text: "hidden vegetable mode" },
      { icon: 'Cookie', text: "cookie meditation" },
      { icon: 'IceCream', text: "ice cream dinner" }
    ]
  },
  lateLuteal: {
    name: 'Volatility Alert',
    description: 'Emotional turbulence ahead. Fasten seatbelts.',
    calendarTooltip: 'WARNING - Mood changes without notice',
    moods: [
      "She's laughing and crying simultaneously",
      "Currently experiencing all emotions",
      "Her feelings have feelings",
      "She cried at a dog video",
      "Emotional stability has left the chat",
      "She's mad at you for dream crimes",
      "Currently on an emotional rollercoaster",
      "She loves you but also questions why",
      "Her mood changes faster than weather",
      "She's emotionally everywhere",
      "Currently unable to explain feelings",
      "She's crying about future problems",
      "Her emotions need a GPS",
      "She's overwhelmed by existing",
      "Currently feeling everything deeply",
      "She hates her clothes and life",
      "Her emotional range: Yes",
      "She's pre-mad about things",
      "Currently collecting feelings",
      "She needs hugs but don't touch her",
      "Her tears have subcategories",
      "She's emotionally preparing",
      "Currently on sensitivity overload",
      "She's upset about theoretical scenarios",
      "Her feelings are doing parkour",
      "She needs support and space",
      "Currently crying at commercials",
      "She's emotionally exhausted",
      "Her mood ring exploded",
      "She's feeling feelings about feelings",
      "Currently in emotional preparation mode",
      "She needs understanding and chocolate"
    ],
    cravings: [
      { icon: 'IceCream', text: "emotional support ice cream" },
      { icon: 'Cookie', text: "feeling cookies required" },
      { icon: 'Candy', text: "chocolate mood stabilizer" },
      { icon: 'Soup', text: "comfort soup ASAP" },
      { icon: 'Coffee', text: "calming tea maybe?" },
      { icon: 'Wheat', text: "bread for every emotion" },
      { icon: 'Cherry', text: "pie for each feeling" },
      { icon: 'Milk', text: "cheese emotional support" },
      { icon: 'Banana', text: "banana bread therapy" },
      { icon: 'Apple', text: "apple comfort dessert" },
      { icon: 'Fish', text: "sushi crying session" },
      { icon: 'Salad', text: "salad of emotions" },
      { icon: 'Egg', text: "scrambled like feelings" },
      { icon: 'Nut', text: "mixed nuts, mixed moods" },
      { icon: 'Carrot', text: "carrot cake feelings" },
      { icon: 'IceCream', text: "cry into ice cream" },
      { icon: 'Cookie', text: "emotional cookie jar" },
      { icon: 'Candy', text: "candy for each mood" },
      { icon: 'Soup', text: "soup for her soul" },
      { icon: 'Coffee', text: "whatever she needs" },
      { icon: 'Wheat', text: "carb comfort loading" },
      { icon: 'Cherry', text: "cherry mood picker" },
      { icon: 'Milk', text: "dairy emotional support" },
      { icon: 'Banana', text: "banana split feelings" },
      { icon: 'Apple', text: "apple pie emotions" },
      { icon: 'Fish', text: "comfort food delivery" },
      { icon: 'Salad', text: "emotions with dressing" },
      { icon: 'Egg', text: "egg comfort classic" },
      { icon: 'Nut', text: "going nuts together" },
      { icon: 'Carrot', text: "vegetable feelings food" },
      { icon: 'IceCream', text: "frozen emotion therapy" },
      { icon: 'Cookie', text: "cookie feeling fest" }
    ]
  },
  premenstrual: {
    name: 'DEFCON 1',
    description: 'Maximum danger. Bring chocolate. Leave chocolate. Run.',
    calendarTooltip: 'DANGER - Maximum caution required',
    moods: [
      "She's a hormone hurricane approaching",
      "Currently accepting tributes only",
      "Her patience account is overdrawn",
      "She's preparing for war",
      "Everything you do is wrong",
      "Currently in pre-destruction mode",
      "She's bloated and dangerous",
      "Her murder eyes are activated",
      "She needs space... like, Mars",
      "Currently plotting your demise",
      "She's one comment from explosion",
      "Her tolerance has expired",
      "She's not speaking, that's safer",
      "Currently radiating danger",
      "She hates everything, especially you",
      "Her rage meter is at 99%",
      "She's basically a time bomb",
      "Currently unavailable for anything",
      "She's considering violence",
      "Her hormones declared war",
      "She needs chocolate and distance",
      "Currently in final boss mode",
      "She's too angry for words",
      "Her patience left the country",
      "She's basically weaponized",
      "Currently accepting silence only",
      "She's entered the danger zone",
      "Her mood is 'stay away'",
      "She's preparing for battle",
      "Currently loading rage mode",
      "She's achieved peak irritation",
      "Emergency protocols required"
    ],
    cravings: [
      { icon: 'Cookie', text: "ALL THE COOKIES NOW" },
      { icon: 'IceCream', text: "ice cream shrine needed" },
      { icon: 'Candy', text: "chocolate fort required" },
      { icon: 'Soup', text: "mac and cheese ocean" },
      { icon: 'Coffee', text: "wine emergency kit" },
      { icon: 'Wheat', text: "bakery on speed dial" },
      { icon: 'Cherry', text: "pie or death situation" },
      { icon: 'Milk', text: "cheese wheel offering" },
      { icon: 'Banana', text: "banana bread wall" },
      { icon: 'Apple', text: "apple destruction pie" },
      { icon: 'Fish', text: "sushi boat solo mission" },
      { icon: 'Salad', text: "salad? prepare for war" },
      { icon: 'Egg', text: "breakfast fortress" },
      { icon: 'Nut', text: "nut butter by gallons" },
      { icon: 'Carrot', text: "carrot cake mountain" },
      { icon: 'Cookie', text: "cookie apocalypse prep" },
      { icon: 'IceCream', text: "ice cream bunker" },
      { icon: 'Candy', text: "candy store robbery" },
      { icon: 'Soup', text: "comfort food tsunami" },
      { icon: 'Coffee', text: "caffeine war chest" },
      { icon: 'Wheat', text: "bread ammunition" },
      { icon: 'Cherry', text: "dessert demanded" },
      { icon: 'Milk', text: "dairy demolition" },
      { icon: 'Banana', text: "banana rage fuel" },
      { icon: 'Apple', text: "apple anything NOW" },
      { icon: 'Fish', text: "emergency sushi" },
      { icon: 'Salad', text: "NOT salad, ever" },
      { icon: 'Egg', text: "egg battle rations" },
      { icon: 'Nut', text: "nuts or YOUR nuts" },
      { icon: 'Carrot', text: "cake or consequences" },
      { icon: 'Cookie', text: "cookie countdown" },
      { icon: 'IceCream', text: "frozen fury food" }
    ]
  }
};

// Helper function to get random phrase while tracking usage
export const getRandomKingPhrase = (phase, type) => {
  const phrases = kingPhrases[phase]?.[type];
  if (!phrases || phrases.length === 0) return null;
  
  // Simple random selection for now
  // TODO: Implement proper phrase tracking to avoid repetition
  const randomIndex = Math.floor(Math.random() * phrases.length);
  return type === 'moods' 
    ? phrases[randomIndex]
    : phrases[randomIndex];
};

// Export phase names for compatibility
export const kingPhaseNames = {
  menstrual: 'Code Red Alert',
  follicular: 'Safe Zone Active',
  ovulation: 'High Energy Warning',
  luteal: 'Patience Level: Low',
  lateLuteal: 'Volatility Alert',
  premenstrual: 'DEFCON 1'
};

// Export UI text specific to King mode
export const kingUIText = {
  modeToggleOn: 'King',
  testModeLabel: 'Test Mode',
  phaseLabel: 'Current Status',
  fertilityLabel: 'Danger Level',
  settingsTitle: 'Settings',
  historyTitle: 'Survival Log',
  todayButton: 'Today',
  dayLabel: 'Day',
  ofLabel: 'of',
  cycleDayLabel: 'Cycle Day',
  tabs: {
    mood: 'Status',
    calendar: 'Danger Calendar',
    history: 'Survival Log',
    settings: 'Settings'
  },
  buttons: {
    save: 'Save Settings',
    cancel: 'Cancel',
    markPeriod: 'Mark Start',
    export: 'Export Data',
    import: 'Import Data'
  },
  labels: {
    cycleLength: 'Cycle Length',
    startDate: 'Cycle Start Date',
    notifications: 'Enable Warnings',
    testMode: 'Test Mode'
  }
};