// Queen/King mode content with sarcastic black humor
// Queen: First-person female perspective
// King: Partner/observer perspective with warnings

export const modeContent = {
  queen: {
    phases: {
      menstrual: {
        name: 'Bloody Hell Week',
        description: 'F*ck this sh*t. Where\'s the chocolate?',
        calendarTooltip: 'The Red Wedding - Approach with caution',
        moods: [
          "I'm basically a crime scene down there",
          "Currently accepting applications for a new uterus",
          "My cramps have cramps",
          "I've eaten everything in a 5-mile radius",
          "Currently identifying as a heating pad",
          "Bloated like a dead whale on a beach",
          "Considering violence as a valid life choice",
          "My back hurts, my boobs hurt, existence hurts",
          "I sneezed and created a horror movie scene",
          "Currently powered by rage and chocolate",
          "If looks could kill, I'd be a serial killer",
          "Everything is stupid and I hate it all",
          "I'm not crying, my eyes are just bleeding too",
          "My uterus is having a temper tantrum",
          "Currently accepting donations of new organs",
          "I've transcended pain and entered a new dimension",
          "Wearing my murder pants today",
          "My hormones are having a rave without me",
          "I'm one inconvenience away from arson",
          "Currently experiencing all emotions simultaneously",
          "My body is a betrayal factory",
          "I'm basically a shark attack victim who survived",
          "Existing is overrated anyway",
          "My pain scale goes to 11 today",
          "I've eaten my body weight in carbs",
          "Currently accepting prayers and chocolate",
          "My uterus is doing its best Alien impression",
          "I'm too tired to be tired",
          "Everything hurts and I'm dying",
          "Currently unavailable due to internal renovation",
          "My body hates me and the feeling is mutual",
          "I'm a delicate f*cking flower, okay?"
        ],
        cravings: [
          { icon: 'Cookie', text: "entire chocolate factory" },
          { icon: 'IceCream', text: "Ben & Jerry's, all flavors" },
          { icon: 'Candy', text: "anything with sugar" },
          { icon: 'Soup', text: "molten lava cake" },
          { icon: 'Coffee', text: "wine, lots of wine" },
          { icon: 'Wheat', text: "entire loaf of bread" },
          { icon: 'Cherry', text: "chocolate-covered everything" },
          { icon: 'Milk', text: "cheese, all the cheese" },
          { icon: 'Banana', text: "french fries dipped in ice cream" },
          { icon: 'Apple', text: "pizza with extra everything" },
          { icon: 'Fish', text: "sushi boat for one" },
          { icon: 'Salad', text: "salad... just kidding, cake" },
          { icon: 'Egg', text: "breakfast for every meal" },
          { icon: 'Nut', text: "Nutella by the spoonful" },
          { icon: 'Carrot', text: "carrot cake counts as vegetables" },
          { icon: 'Cookie', text: "cookie dough, raw" },
          { icon: 'IceCream', text: "milkshake IV drip" },
          { icon: 'Candy', text: "Halloween candy stash" },
          { icon: 'Soup', text: "mac and cheese swimming pool" },
          { icon: 'Coffee', text: "coffee with a side of coffee" },
          { icon: 'Wheat', text: "pasta mountain" },
          { icon: 'Cherry', text: "pie, whole pie" },
          { icon: 'Milk', text: "chocolate milk river" },
          { icon: 'Banana', text: "banana split for breakfast" },
          { icon: 'Apple', text: "caramel apples, dozen" },
          { icon: 'Fish', text: "fish and chips and chips" },
          { icon: 'Salad', text: "Caesar salad, hold the salad" },
          { icon: 'Egg', text: "eggs Benedict on everything" },
          { icon: 'Nut', text: "peanut butter from the jar" },
          { icon: 'Carrot', text: "carbs, just carbs" },
          { icon: 'Cookie', text: "grandma's cookie jar" },
          { icon: 'IceCream', text: "ice cream for dinner" }
        ]
      },
      follicular: {
        name: 'Finally Got My Sh*t Together',
        description: 'Look at me being a functional human being!',
        calendarTooltip: 'She\'s back to normal-ish',
        moods: [
          "I'm practically a Disney princess today",
          "My skin is glowing and I'm not dying",
          "Suddenly I remember why I like being alive",
          "I cleaned something without crying",
          "I can see my ankles again!",
          "My jeans fit and I'm not homicidal",
          "I actually want to leave the house",
          "Look at me adulting like a boss",
          "I remembered to shower AND use soap",
          "My brain works again, it's a miracle",
          "I can form complete sentences!",
          "Productivity level: Actually doing sh*t",
          "I don't hate everyone today",
          "My body and I are on speaking terms",
          "I exercised and didn't die",
          "I'm basically Wonder Woman right now",
          "Energy levels: Could fight a bear",
          "I'm so functional it's scary",
          "Watch me conquer the world",
          "I remembered what happiness feels like",
          "My hormones are finally behaving",
          "I can tolerate other humans again",
          "Look at me making plans and sh*t",
          "I'm basically a productivity goddess",
          "My mood is so stable it's suspicious",
          "I cleaned my room without having a breakdown",
          "I'm nice to people on purpose",
          "Life doesn't suck today",
          "I'm crushing it at this whole existing thing",
          "My energy could power a small city",
          "I remembered to eat vegetables",
          "I'm so together I scare myself"
        ],
        cravings: [
          { icon: 'Salad', text: "actual vegetables" },
          { icon: 'Apple', text: "fruit that isn't covered in chocolate" },
          { icon: 'Fish', text: "grilled salmon like a health goddess" },
          { icon: 'Egg', text: "protein-packed breakfast" },
          { icon: 'Carrot', text: "smoothie bowl aesthetic" },
          { icon: 'Nut', text: "almonds like a responsible adult" },
          { icon: 'Wheat', text: "whole grains and sh*t" },
          { icon: 'Milk', text: "Greek yogurt parfait" },
          { icon: 'Cherry', text: "antioxidant berries" },
          { icon: 'Banana', text: "pre-workout banana" },
          { icon: 'Soup', text: "vegetable soup I made myself" },
          { icon: 'Coffee', text: "green tea like a zen master" },
          { icon: 'Salad', text: "kale salad (who am I?)" },
          { icon: 'Apple', text: "apple slices with almond butter" },
          { icon: 'Fish', text: "poke bowl perfection" },
          { icon: 'Egg', text: "egg white omelet" },
          { icon: 'Carrot', text: "veggie sticks and hummus" },
          { icon: 'Nut', text: "trail mix for hiking" },
          { icon: 'Wheat', text: "quinoa bowl queen" },
          { icon: 'Milk', text: "probiotic yogurt" },
          { icon: 'Cherry', text: "fresh fruit salad" },
          { icon: 'Banana', text: "banana nice cream" },
          { icon: 'Soup', text: "bone broth like a wellness guru" },
          { icon: 'Coffee', text: "matcha latte vibes" },
          { icon: 'Salad', text: "Buddha bowl bliss" },
          { icon: 'Apple', text: "green juice (I'm that b*tch)" },
          { icon: 'Fish', text: "seared tuna steak" },
          { icon: 'Egg', text: "poached eggs on avocado toast" },
          { icon: 'Carrot', text: "roasted vegetables" },
          { icon: 'Nut', text: "cashew cheese (fancy!)" },
          { icon: 'Wheat', text: "overnight oats" },
          { icon: 'Milk', text: "cottage cheese power snack" }
        ]
      },
      ovulation: {
        name: 'Horny AF',
        description: 'Is it hot in here or is it just my hormones?',
        calendarTooltip: 'Baby-making factory is OPEN',
        moods: [
          "Everything is sexy, even furniture",
          "My ovaries are throwing a party",
          "I'd climb my partner like a tree",
          "Currently radiating big fertile energy",
          "My body is ready to make terrible decisions",
          "Feeling myself in every possible way",
          "My hormones are writing checks my body can't cash",
          "I'm basically a fertility goddess right now",
          "Everything turns me on, including this text",
          "My eggs are doing the cha-cha",
          "I could seduce a lamp post",
          "Currently accepting applications for baby daddy",
          "My pheromones could start a riot",
          "I'm so fertile plants grow when I walk by",
          "My body is screaming 'PROCREATE!'",
          "I'm basically in heat",
          "My ovaries have their own agenda",
          "Catch me making eye contact with everyone",
          "I'm radiating 'come hither' energy",
          "My body is a wonderland (literally)",
          "Currently at peak human performance",
          "I could get pregnant from a handshake",
          "My eggs are having a going away party",
          "Everything is foreplay right now",
          "I'm basically a walking biology textbook",
          "My hormones are off the charts",
          "Currently operating at maximum fertility",
          "I'm so ready nature is impressed",
          "My body is open for business",
          "Peak baby-making hours in effect",
          "I'm basically evolution's favorite",
          "My ovaries deserve an award"
        ],
        cravings: [
          { icon: 'Cherry', text: "aphrodisiac foods" },
          { icon: 'Banana', text: "suggestively shaped fruits" },
          { icon: 'Fish', text: "oysters (wink wink)" },
          { icon: 'Candy', text: "chocolate-covered strawberries" },
          { icon: 'Coffee', text: "espresso for stamina" },
          { icon: 'Nut', text: "nuts for... energy" },
          { icon: 'Egg', text: "eggs (how fitting)" },
          { icon: 'Milk', text: "whipped cream possibilities" },
          { icon: 'Apple', text: "forbidden fruit vibes" },
          { icon: 'Wheat', text: "carbs for endurance" },
          { icon: 'IceCream', text: "something to lick" },
          { icon: 'Cookie', text: "fortune cookies with spicy fortunes" },
          { icon: 'Salad', text: "cucumber salad (hmm)" },
          { icon: 'Soup', text: "hot and steamy anything" },
          { icon: 'Carrot', text: "vitamin-rich veggies" },
          { icon: 'Cherry', text: "cherries to pop" },
          { icon: 'Banana', text: "potassium for stamina" },
          { icon: 'Fish', text: "sushi date night" },
          { icon: 'Candy', text: "sweet treats for sweet times" },
          { icon: 'Coffee', text: "coffee date energy" },
          { icon: 'Nut', text: "Brazil nuts for fertility" },
          { icon: 'Egg', text: "protein power breakfast" },
          { icon: 'Milk', text: "calcium for strong... bones" },
          { icon: 'Apple', text: "juicy fruits" },
          { icon: 'Wheat', text: "morning-after pancakes" },
          { icon: 'IceCream', text: "shared desserts" },
          { icon: 'Cookie', text: "midnight snacks" },
          { icon: 'Salad', text: "light meals for agility" },
          { icon: 'Soup', text: "room service menu" },
          { icon: 'Carrot', text: "energy boosting snacks" },
          { icon: 'Cherry', text: "romantic fruit platter" },
          { icon: 'Banana', text: "breakfast in bed fuel" }
        ]
      },
      luteal: {
        name: 'Getting Real Tired of This BS',
        description: 'Starting to question my life choices...',
        calendarTooltip: 'Patience wearing thin',
        moods: [
          "My patience has left the building",
          "Everything is annoying, especially breathing",
          "I'm not mad, I'm just disappointed in everyone",
          "My tolerance for BS is at zero",
          "Currently accepting apologies for existing",
          "I'm fine. Everything is fine. *eye twitches*",
          "My give-a-f*ck is broken",
          "Slowly morphing into my final form",
          "I can feel my soul leaving my body",
          "Everyone is wrong about everything",
          "My face hurts from fake smiling",
          "Currently one comment away from snapping",
          "I'm not antisocial, everyone just sucks",
          "My energy has been recalled by the manufacturer",
          "Everything is a personal attack",
          "I'm running on fumes and spite",
          "My mood ring just burst into flames",
          "Currently unavailable for human interaction",
          "I've tried being nice, it's overrated",
          "My brain fog has brain fog",
          "I'm not grumpy, this is just my face now",
          "Everything requires too much effort",
          "My last nerve is hanging by a thread",
          "I'm basically a grumpy cat in human form",
          "Currently accepting bribes to be nice",
          "My hormones are plotting against me",
          "I'm tired of being tired",
          "Everything is exhausting, especially people",
          "My enthusiasm has filed for divorce",
          "I'm one minor inconvenience from a meltdown",
          "Currently operating at 10% capacity",
          "My social battery is in the negative"
        ],
        cravings: [
          { icon: 'Cookie', text: "comfort cookies" },
          { icon: 'IceCream', text: "ice cream for dinner" },
          { icon: 'Candy', text: "all the chocolate" },
          { icon: 'Soup', text: "carb-loaded pasta" },
          { icon: 'Coffee', text: "caffeine IV drip" },
          { icon: 'Wheat', text: "bread, just bread" },
          { icon: 'Cherry', text: "pie for breakfast" },
          { icon: 'Milk', text: "cheese platter for one" },
          { icon: 'Banana', text: "banana bread loaf" },
          { icon: 'Apple', text: "apple pie à la mode" },
          { icon: 'Fish', text: "fish and chips comfort" },
          { icon: 'Salad', text: "Caesar salad (mostly croutons)" },
          { icon: 'Egg', text: "breakfast all day" },
          { icon: 'Nut', text: "Nutella from the jar" },
          { icon: 'Carrot', text: "carrot cake therapy" },
          { icon: 'Cookie', text: "cookie dough medicine" },
          { icon: 'IceCream', text: "emotional support ice cream" },
          { icon: 'Candy', text: "candy stash raiding" },
          { icon: 'Soup', text: "comfort soup bowl" },
          { icon: 'Coffee', text: "extra shot everything" },
          { icon: 'Wheat', text: "garlic bread heaven" },
          { icon: 'Cherry', text: "cherry cobbler comfort" },
          { icon: 'Milk', text: "hot chocolate therapy" },
          { icon: 'Banana', text: "banana split because why not" },
          { icon: 'Apple', text: "caramel apple slices" },
          { icon: 'Fish', text: "comfort food sushi" },
          { icon: 'Salad', text: "taco salad (heavy on taco)" },
          { icon: 'Egg', text: "eggs Benedict therapy" },
          { icon: 'Nut', text: "mixed nuts for sanity" },
          { icon: 'Carrot', text: "vegetable tempura" },
          { icon: 'Cookie', text: "emergency cookie stash" },
          { icon: 'IceCream', text: "gelato for the soul" }
        ]
      },
      lateLuteal: {
        name: 'Pre-Chaos Mood Swings',
        description: 'Don\'t even look at me wrong today',
        calendarTooltip: 'Emotional rollercoaster in progress',
        moods: [
          "I'm laughing, I'm crying, I'm a mess",
          "My emotions are having a battle royale",
          "Currently experiencing all feelings at once",
          "I cried at a commercial for toilet paper",
          "My mood changes faster than I can track",
          "Everything is either hilarious or tragic",
          "I'm basically a human mood ring",
          "My emotions have emotions",
          "Currently unable to regulate anything",
          "I'm fine, I'm not fine, I'm fine again",
          "My feelings are doing parkour",
          "Everything makes me cry, including this",
          "I'm an emotional tornado",
          "My mood swings have mood swings",
          "Currently experiencing technical difficulties",
          "I laughed so hard I cried, then just cried",
          "My emotions are in a blender",
          "I'm basically a feelings factory",
          "Everything is overwhelming and underwhelming",
          "My emotional stability has left the chat",
          "I'm a walking contradiction",
          "Currently feeling every feeling ever felt",
          "My hormones are drunk",
          "I'm emotionally exhausted from emotions",
          "Everything is beautiful and terrible",
          "My feelings need a GPS",
          "I'm basically a soap opera",
          "Currently crying about future events",
          "My emotions are playing ping pong",
          "I'm too emotional to be emotional",
          "Everything hits different today",
          "My mood is a mystery to everyone, including me"
        ],
        cravings: [
          { icon: 'IceCream', text: "emotional eating ice cream" },
          { icon: 'Cookie', text: "cry-eating cookies" },
          { icon: 'Candy', text: "mood swing chocolate" },
          { icon: 'Soup', text: "comfort food marathon" },
          { icon: 'Coffee', text: "stress coffee overdose" },
          { icon: 'Wheat', text: "feelings pasta" },
          { icon: 'Cherry', text: "emotional support pie" },
          { icon: 'Milk', text: "cheese for every mood" },
          { icon: 'Banana', text: "banana comfort bread" },
          { icon: 'Apple', text: "apple crisp feelings" },
          { icon: 'Fish', text: "sushi emotional support" },
          { icon: 'Salad', text: "salad but make it fried" },
          { icon: 'Egg', text: "scrambled like my emotions" },
          { icon: 'Nut', text: "stress eating nuts" },
          { icon: 'Carrot', text: "carrot cake therapy" },
          { icon: 'IceCream', text: "cry into ice cream" },
          { icon: 'Cookie', text: "emotional support cookies" },
          { icon: 'Candy', text: "candy for each feeling" },
          { icon: 'Soup', text: "soup for the soul" },
          { icon: 'Coffee', text: "anxiety coffee combo" },
          { icon: 'Wheat', text: "bread for every mood" },
          { icon: 'Cherry', text: "cherry stress tart" },
          { icon: 'Milk', text: "milkshake feelings" },
          { icon: 'Banana', text: "banana split personality" },
          { icon: 'Apple', text: "apple turnover emotions" },
          { icon: 'Fish', text: "fish tacos for tears" },
          { icon: 'Salad', text: "emotional salad bar" },
          { icon: 'Egg', text: "deviled eggs for my mood" },
          { icon: 'Nut', text: "going nuts snack mix" },
          { icon: 'Carrot', text: "vegetables but fried" },
          { icon: 'IceCream', text: "frozen feelings therapy" },
          { icon: 'Cookie', text: "batch of feeling cookies" }
        ]
      },
      premenstrual: {
        name: 'Apocalypse Countdown',
        description: 'If you value your life, bring snacks',
        calendarTooltip: 'DEFCON 1 - Maximum alert',
        moods: [
          "I'm a ticking time bomb of hormones",
          "Currently accepting tribute in chocolate form",
          "My uterus is preparing for war",
          "Everything hurts and everyone sucks",
          "I'm bloated like a rage balloon",
          "My body is a prison of discomfort",
          "Currently plotting everyone's demise",
          "I can feel the storm coming",
          "My patience expired 3 days ago",
          "Everything is a personal attack on me",
          "I'm basically a hormone hurricane",
          "My mood is set to 'destroy'",
          "Currently unavailable due to impending doom",
          "I'm one breath away from violence",
          "My body is betraying me again",
          "Everything is stupid, especially this",
          "I'm basically a grumpy balloon",
          "My rage is charging to 100%",
          "Currently accepting distance and snacks",
          "I can feel my sanity slipping",
          "Everything is offensive to my existence",
          "I'm a danger to myself and others",
          "My hormones are staging a coup",
          "Currently in my villain era",
          "I'm too angry to be angry",
          "Everything requires too much existence",
          "My body is preparing for battle",
          "Currently loading: Rage Mode",
          "I'm basically a hormonal time bomb",
          "Everything is wrong with everything",
          "My uterus has declared war",
          "I'm ready to burn it all down"
        ],
        cravings: [
          { icon: 'Cookie', text: "ALL THE COOKIES" },
          { icon: 'IceCream', text: "ice cream by the gallon" },
          { icon: 'Candy', text: "chocolate emergency kit" },
          { icon: 'Soup', text: "mac and cheese bath" },
          { icon: 'Coffee', text: "wine and coffee combo" },
          { icon: 'Wheat', text: "entire bakery" },
          { icon: 'Cherry', text: "pie, whole pie, now" },
          { icon: 'Milk', text: "cheese wheel for one" },
          { icon: 'Banana', text: "banana everything" },
          { icon: 'Apple', text: "caramel apple revenge" },
          { icon: 'Fish', text: "sushi boat solo" },
          { icon: 'Salad', text: "salad? LOL. Pizza." },
          { icon: 'Egg', text: "breakfast rage fuel" },
          { icon: 'Nut', text: "nut butter jar therapy" },
          { icon: 'Carrot', text: "carbs disguised as vegetables" },
          { icon: 'Cookie', text: "cookie apocalypse" },
          { icon: 'IceCream', text: "ice cream fortress" },
          { icon: 'Candy', text: "candy store raid" },
          { icon: 'Soup', text: "soup pool to swim in" },
          { icon: 'Coffee', text: "caffeine overdose plan" },
          { icon: 'Wheat', text: "bread fortress building" },
          { icon: 'Cherry', text: "cherry bomb desserts" },
          { icon: 'Milk', text: "dairy destruction" },
          { icon: 'Banana', text: "banana rage bread" },
          { icon: 'Apple', text: "apple destruction pie" },
          { icon: 'Fish', text: "angry sushi ordering" },
          { icon: 'Salad', text: "salad... psyche! Burgers." },
          { icon: 'Egg', text: "egg everything attack" },
          { icon: 'Nut', text: "nuts about going nuts" },
          { icon: 'Carrot', text: "carrot cake rampage" },
          { icon: 'Cookie', text: "cookie monster mode" },
          { icon: 'IceCream', text: "frozen fury food" }
        ]
      }
    },
    ui: {
      tabs: {
        mood: 'Mood',
        calendar: 'Calendar',
        history: 'History',
        settings: 'Settings'
      },
      buttons: {
        save: 'Save this Sh*t',
        cancel: 'F*ck It',
        markPeriod: 'Red Wedding Started',
        export: 'Export My Drama',
        import: 'Import Old Drama'
      },
      labels: {
        cycleLength: 'How Long This Hell Lasts',
        startDate: 'Last Bloodbath Started',
        notifications: 'Remind Me of My Suffering',
        testMode: 'Time Travel Mode'
      }
    }
  },
  king: {
    phases: {
      menstrual: {
        name: 'Code Red Alert',
        description: 'Approach with chocolate. And caution.',
        calendarTooltip: 'DANGER ZONE - Bring offerings',
        moods: [
          "She's losing blood, don't make her lose her mind",
          "Currently unavailable for rational discussion",
          "Chocolate is not optional, it's survival",
          "She's in pain, you're in danger",
          "Emergency snack protocols activated",
          "Her uterus is angry, tread carefully",
          "This is not a drill, bring ice cream",
          "She needs space... and snacks",
          "Currently operating on emergency backup hormones",
          "Approach only with offerings",
          "Her patience has been temporarily discontinued",
          "Warning: Emotional range set to 'ALL'",
          "She's not mean, she's in pain",
          "Survival tip: Agree with everything",
          "Her body is staging a rebellion",
          "Code Red: Literally and figuratively",
          "She's fighting a battle you can't see",
          "Comfort level required: Maximum",
          "She needs heat packs and understanding",
          "Currently experiencing technical difficulties",
          "Her murder face is not personal",
          "Supplies needed: Chocolate, patience, more chocolate",
          "She's not dramatic, she's in pain",
          "Warning: Logic temporarily offline",
          "She's basically bleeding to death monthly",
          "Emergency protocols: Snacks and silence",
          "Her body hates her, don't join in",
          "Currently powered by pain and rage",
          "She's a warrior, treat her like one",
          "Survival mode: Just be nice",
          "Her uterus is having a tantrum",
          "Approach rating: Extremely hazardous"
        ],
        cravings: [
          { icon: 'Cookie', text: "emergency cookie delivery" },
          { icon: 'IceCream', text: "ice cream peace offering" },
          { icon: 'Candy', text: "chocolate survival kit" },
          { icon: 'Soup', text: "comfort food parade" },
          { icon: 'Coffee', text: "whatever she wants drink" },
          { icon: 'Wheat', text: "carb mountain delivery" },
          { icon: 'Cherry', text: "dessert first policy" },
          { icon: 'Milk', text: "cheese board distraction" },
          { icon: 'Banana', text: "banana bread bribery" },
          { icon: 'Apple', text: "apple pie peace treaty" },
          { icon: 'Fish', text: "sushi silence bribe" },
          { icon: 'Salad', text: "salad? Are you insane?" },
          { icon: 'Egg', text: "breakfast in bed mandatory" },
          { icon: 'Nut', text: "nut butter emergency jar" },
          { icon: 'Carrot', text: "cake disguised as vegetables" },
          { icon: 'Cookie', text: "cookie ammunition" },
          { icon: 'IceCream', text: "ice cream diplomacy" },
          { icon: 'Candy', text: "candy peacekeeping force" },
          { icon: 'Soup', text: "soup for her soul" },
          { icon: 'Coffee', text: "coffee on demand" },
          { icon: 'Wheat', text: "bread fortress supplies" },
          { icon: 'Cherry', text: "cherry on top everything" },
          { icon: 'Milk', text: "dairy delivery service" },
          { icon: 'Banana', text: "banana split negotiations" },
          { icon: 'Apple', text: "apple turnover truce" },
          { icon: 'Fish', text: "fish and silence combo" },
          { icon: 'Salad', text: "pizza disguised as salad" },
          { icon: 'Egg', text: "egg-cellent distraction" },
          { icon: 'Nut', text: "nuts for her sanity" },
          { icon: 'Carrot', text: "carrot cake camouflage" },
          { icon: 'Cookie', text: "cookie peace talks" },
          { icon: 'IceCream', text: "frozen treaty treats" }
        ]
      },
      follicular: {
        name: 'Safe Zone Active',
        description: 'She\'s back! Quick, make plans!',
        calendarTooltip: 'Safe zone - She likes you again',
        moods: [
          "She remembers why she keeps you around",
          "Currently accepting compliments and date nights",
          "Her energy is back, use it wisely",
          "She's actually listening when you talk",
          "This is your window for difficult conversations",
          "She's in a good mood, don't waste it",
          "Currently available for adventures",
          "Her patience has been restored",
          "She actually wants to do things",
          "Quick! She's feeling social!",
          "Her smile is genuine again",
          "She's not plotting your death anymore",
          "Currently open to suggestions",
          "She remembers she loves you",
          "This is peak girlfriend material time",
          "She's actually interested in your day",
          "Her energy could power the city",
          "She wants to go out! Alert the media!",
          "Currently accepting physical affection",
          "She's laughing at your jokes again",
          "Her motivation has returned from vacation",
          "She's making plans that include you",
          "Currently radiating positive energy",
          "She cleaned something voluntarily",
          "Her appetite for life is back",
          "She's singing in the shower again",
          "Currently available for couple activities",
          "She suggested date night first",
          "Her mood ring says 'happy'",
          "She's actually excited about things",
          "Currently in girlfriend of the year mode",
          "She wants to try that new restaurant"
        ],
        cravings: [
          { icon: 'Salad', text: "she wants healthy food?!" },
          { icon: 'Apple', text: "fruit without chocolate coating" },
          { icon: 'Fish', text: "fancy dinner opportunity" },
          { icon: 'Egg', text: "brunch date incoming" },
          { icon: 'Carrot', text: "she's eating vegetables willingly" },
          { icon: 'Nut', text: "healthy snacks phase" },
          { icon: 'Wheat', text: "she'll share your pizza" },
          { icon: 'Milk', text: "smoothie dates possible" },
          { icon: 'Cherry', text: "fruit for dessert works" },
          { icon: 'Banana', text: "gym partnership renewed" },
          { icon: 'Soup', text: "cooking together time" },
          { icon: 'Coffee', text: "coffee dates approved" },
          { icon: 'Salad', text: "restaurant adventures" },
          { icon: 'Apple', text: "farmers market trips" },
          { icon: 'Fish', text: "sushi date night" },
          { icon: 'Egg', text: "breakfast together goals" },
          { icon: 'Carrot', text: "healthy meal prep partner" },
          { icon: 'Nut', text: "trail mix hiking buddy" },
          { icon: 'Wheat', text: "bakery visits allowed" },
          { icon: 'Milk', text: "latte art appreciation" },
          { icon: 'Cherry', text: "picking fruit together" },
          { icon: 'Banana', text: "smoothie bowl dates" },
          { icon: 'Soup', text: "soup and conversation" },
          { icon: 'Coffee', text: "morning coffee ritual" },
          { icon: 'Salad', text: "trying new places" },
          { icon: 'Apple', text: "healthy choice support" },
          { icon: 'Fish', text: "cooking class couple" },
          { icon: 'Egg', text: "weekend brunch plans" },
          { icon: 'Carrot', text: "grocery shopping together" },
          { icon: 'Nut', text: "sharing snacks happily" },
          { icon: 'Wheat', text: "bread making adventures" },
          { icon: 'Milk', text: "cheese tasting dates" }
        ]
      },
      ovulation: {
        name: 'High Energy Warning',
        description: 'High energy alert. She\'s feeling good.',
        calendarTooltip: 'GREEN LIGHT - Safe to approach',
        moods: [
          "She's looking at you like a snack",
          "Currently accepting all applications",
          "Her hormones called, they want you",
          "This is not a drill, she's ready",
          "She's basically hunting you",
          "Currently radiating 'come hither' energy",
          "She's interested in... everything",
          "Her body has one agenda today",
          "She's giving you THE look",
          "Currently open for business",
          "She's more interested in you than Netflix",
          "Her attraction level: Maximum",
          "She actually initiated",
          "Currently in goddess mode",
          "She's wearing THAT outfit",
          "Her flirt game is strong",
          "She keeps touching you",
          "Currently broadcasting availability",
          "She suggested an early night",
          "Her pheromones are in overdrive",
          "She's laughing at ALL your jokes",
          "Currently finding you irresistible",
          "She turned off the TV",
          "Her energy is... focused",
          "She's making all the moves",
          "Currently in seduction mode",
          "She bought new lingerie",
          "Her bedroom eyes are activated",
          "She's very... affectionate",
          "Currently prioritizing couple time",
          "She keeps suggesting 'naps'",
          "Her interest level: Off the charts"
        ],
        cravings: [
          { icon: 'Cherry', text: "aphrodisiac menu planning" },
          { icon: 'Banana', text: "energy fuel required" },
          { icon: 'Fish', text: "oyster bar visit?" },
          { icon: 'Candy', text: "chocolate and champagne" },
          { icon: 'Coffee', text: "energy drinks on standby" },
          { icon: 'Nut', text: "stamina snacks needed" },
          { icon: 'Egg', text: "protein for... activities" },
          { icon: 'Milk', text: "calcium for... reasons" },
          { icon: 'Apple', text: "forbidden fruit mood" },
          { icon: 'Wheat', text: "carbo-loading required" },
          { icon: 'IceCream', text: "dessert in bed menu" },
          { icon: 'Cookie', text: "midnight snack prep" },
          { icon: 'Salad', text: "light dinners only" },
          { icon: 'Soup', text: "quick meal solutions" },
          { icon: 'Carrot', text: "vitamin boost needed" },
          { icon: 'Cherry', text: "cherry metaphors" },
          { icon: 'Banana', text: "potassium reserves" },
          { icon: 'Fish', text: "romantic dinner plans" },
          { icon: 'Candy', text: "sweet treats after" },
          { icon: 'Coffee', text: "morning after coffee" },
          { icon: 'Nut', text: "energy bar stash" },
          { icon: 'Egg', text: "breakfast in bed prep" },
          { icon: 'Milk', text: "hydration station" },
          { icon: 'Apple', text: "healthy quick bites" },
          { icon: 'Wheat', text: "easy meals planned" },
          { icon: 'IceCream', text: "celebration desserts" },
          { icon: 'Cookie', text: "sugar rush ready" },
          { icon: 'Salad', text: "keeping it light" },
          { icon: 'Soup', text: "room service backup" },
          { icon: 'Carrot', text: "energy vegetables" },
          { icon: 'Cherry', text: "romantic fruit plate" },
          { icon: 'Banana', text: "morning smoothies" }
        ]
      },
      luteal: {
        name: 'Patience Level: Low',
        description: 'Her patience is running low. Proceed carefully.',
        calendarTooltip: 'CAUTION - Tolerance levels dropping',
        moods: [
          "She's starting to find you annoying",
          "Currently running low on patience",
          "Her fake smile is getting tired",
          "She needs more space than NASA",
          "Currently questioning all life choices",
          "She's not mad, just... disappointed",
          "Her energy bill came due",
          "She's entering hibernation mode",
          "Currently unavailable for stupidity",
          "She's practicing selective hearing",
          "Her tolerance is at 25%",
          "She needs a nap and silence",
          "Currently in 'don't push it' mode",
          "She's too tired to pretend",
          "Her social battery is dying",
          "She's considering a solo vacation",
          "Currently operating on reserve power",
          "She's not ignoring you, just resting",
          "Her enthusiasm has left the building",
          "She needs Netflix, not chill",
          "Currently in energy-saving mode",
          "She's rationing her niceness",
          "Her smile muscles are tired",
          "She's choosing battles wisely",
          "Currently accepting space and snacks",
          "She's not antisocial, just selective",
          "Her 'give a damn' is broken",
          "She needs recharging time",
          "Currently on emotional battery saver",
          "She's preparing for the storm",
          "Her mood is 'meh' at best",
          "She's saving energy for survival"
        ],
        cravings: [
          { icon: 'Cookie', text: "comfort food incoming" },
          { icon: 'IceCream', text: "ice cream peace offering" },
          { icon: 'Candy', text: "chocolate first aid kit" },
          { icon: 'Soup', text: "warm comfort required" },
          { icon: 'Coffee', text: "caffeine IV needed" },
          { icon: 'Wheat', text: "carb loading phase" },
          { icon: 'Cherry', text: "dessert therapy time" },
          { icon: 'Milk', text: "cheese plate solo" },
          { icon: 'Banana', text: "banana bread comfort" },
          { icon: 'Apple', text: "baked goods only" },
          { icon: 'Fish', text: "takeout saves lives" },
          { icon: 'Salad', text: "salad? Not today" },
          { icon: 'Egg', text: "breakfast for dinner" },
          { icon: 'Nut', text: "snack stockpiling" },
          { icon: 'Carrot', text: "vegetables in cake form" },
          { icon: 'Cookie', text: "cookie emergency" },
          { icon: 'IceCream', text: "frozen feelings food" },
          { icon: 'Candy', text: "candy stash raiding" },
          { icon: 'Soup', text: "soup and solitude" },
          { icon: 'Coffee', text: "coffee dependency rising" },
          { icon: 'Wheat', text: "bread is life now" },
          { icon: 'Cherry', text: "pie fixes everything" },
          { icon: 'Milk', text: "dairy comfort zone" },
          { icon: 'Banana', text: "banana everything phase" },
          { icon: 'Apple', text: "apple crisp mood" },
          { icon: 'Fish', text: "easy dinner solutions" },
          { icon: 'Salad', text: "pizza renamed salad" },
          { icon: 'Egg', text: "simple foods only" },
          { icon: 'Nut', text: "nut butter therapy" },
          { icon: 'Carrot', text: "hidden vegetable mode" },
          { icon: 'Cookie', text: "cookie meditation" },
          { icon: 'IceCream', text: "ice cream dinner" }
        ]
      },
      lateLuteal: {
        name: 'Volatility Alert',
        description: 'Emotional turbulence ahead. Fasten seatbelts.',
        calendarTooltip: 'WARNING - Mood changes without notice',
        moods: [
          "She's laughing and crying simultaneously",
          "Currently experiencing all emotions",
          "Her feelings have feelings",
          "She cried at a dog video",
          "Emotional stability has left the chat",
          "She's mad at you for dream crimes",
          "Currently on an emotional rollercoaster",
          "She loves you but also questions why",
          "Her mood changes faster than weather",
          "She's emotionally everywhere",
          "Currently unable to explain feelings",
          "She's crying about future problems",
          "Her emotions need a GPS",
          "She's overwhelmed by existing",
          "Currently feeling everything deeply",
          "She hates her clothes and life",
          "Her emotional range: Yes",
          "She's pre-mad about things",
          "Currently collecting feelings",
          "She needs hugs but don't touch her",
          "Her tears have subcategories",
          "She's emotionally preparing",
          "Currently on sensitivity overload",
          "She's upset about theoretical scenarios",
          "Her feelings are doing parkour",
          "She needs support and space",
          "Currently crying at commercials",
          "She's emotionally exhausted",
          "Her mood ring exploded",
          "She's feeling feelings about feelings",
          "Currently in emotional preparation mode",
          "She needs understanding and chocolate"
        ],
        cravings: [
          { icon: 'IceCream', text: "emotional support ice cream" },
          { icon: 'Cookie', text: "feeling cookies required" },
          { icon: 'Candy', text: "chocolate mood stabilizer" },
          { icon: 'Soup', text: "comfort soup ASAP" },
          { icon: 'Coffee', text: "calming tea maybe?" },
          { icon: 'Wheat', text: "bread for every emotion" },
          { icon: 'Cherry', text: "pie for each feeling" },
          { icon: 'Milk', text: "cheese emotional support" },
          { icon: 'Banana', text: "banana bread therapy" },
          { icon: 'Apple', text: "apple comfort dessert" },
          { icon: 'Fish', text: "sushi crying session" },
          { icon: 'Salad', text: "salad of emotions" },
          { icon: 'Egg', text: "scrambled like feelings" },
          { icon: 'Nut', text: "mixed nuts, mixed moods" },
          { icon: 'Carrot', text: "carrot cake feelings" },
          { icon: 'IceCream', text: "cry into ice cream" },
          { icon: 'Cookie', text: "emotional cookie jar" },
          { icon: 'Candy', text: "candy for each mood" },
          { icon: 'Soup', text: "soup for her soul" },
          { icon: 'Coffee', text: "whatever she needs" },
          { icon: 'Wheat', text: "carb comfort loading" },
          { icon: 'Cherry', text: "cherry mood picker" },
          { icon: 'Milk', text: "dairy emotional support" },
          { icon: 'Banana', text: "banana split feelings" },
          { icon: 'Apple', text: "apple pie emotions" },
          { icon: 'Fish', text: "comfort food delivery" },
          { icon: 'Salad', text: "emotions with dressing" },
          { icon: 'Egg', text: "egg comfort classic" },
          { icon: 'Nut', text: "going nuts together" },
          { icon: 'Carrot', text: "vegetable feelings food" },
          { icon: 'IceCream', text: "frozen emotion therapy" },
          { icon: 'Cookie', text: "cookie feeling fest" }
        ]
      },
      premenstrual: {
        name: 'DEFCON 1',
        description: 'Maximum danger. Bring chocolate. Leave chocolate. Run.',
        calendarTooltip: 'DANGER - Maximum caution required',
        moods: [
          "She's a hormone hurricane approaching",
          "Currently accepting tributes only",
          "Her patience account is overdrawn",
          "She's preparing for war",
          "Everything you do is wrong",
          "Currently in pre-destruction mode",
          "She's bloated and dangerous",
          "Her murder eyes are activated",
          "She needs space... like, Mars",
          "Currently plotting your demise",
          "She's one comment from explosion",
          "Her tolerance has expired",
          "She's not speaking, that's safer",
          "Currently radiating danger",
          "She hates everything, especially you",
          "Her rage meter is at 99%",
          "She's basically a time bomb",
          "Currently unavailable for anything",
          "She's considering violence",
          "Her hormones declared war",
          "She needs chocolate and distance",
          "Currently in final boss mode",
          "She's too angry for words",
          "Her patience left the country",
          "She's basically weaponized",
          "Currently accepting silence only",
          "She's entered the danger zone",
          "Her mood is 'stay away'",
          "She's preparing for battle",
          "Currently loading rage mode",
          "She's achieved peak irritation",
          "Emergency protocols required"
        ],
        cravings: [
          { icon: 'Cookie', text: "ALL THE COOKIES NOW" },
          { icon: 'IceCream', text: "ice cream shrine needed" },
          { icon: 'Candy', text: "chocolate fort required" },
          { icon: 'Soup', text: "mac and cheese ocean" },
          { icon: 'Coffee', text: "wine emergency kit" },
          { icon: 'Wheat', text: "bakery on speed dial" },
          { icon: 'Cherry', text: "pie or death situation" },
          { icon: 'Milk', text: "cheese wheel offering" },
          { icon: 'Banana', text: "banana bread wall" },
          { icon: 'Apple', text: "apple destruction pie" },
          { icon: 'Fish', text: "sushi boat solo mission" },
          { icon: 'Salad', text: "salad? prepare for war" },
          { icon: 'Egg', text: "breakfast fortress" },
          { icon: 'Nut', text: "nut butter by gallons" },
          { icon: 'Carrot', text: "carrot cake mountain" },
          { icon: 'Cookie', text: "cookie apocalypse prep" },
          { icon: 'IceCream', text: "ice cream bunker" },
          { icon: 'Candy', text: "candy store robbery" },
          { icon: 'Soup', text: "comfort food tsunami" },
          { icon: 'Coffee', text: "caffeine war chest" },
          { icon: 'Wheat', text: "bread ammunition" },
          { icon: 'Cherry', text: "dessert demanded" },
          { icon: 'Milk', text: "dairy demolition" },
          { icon: 'Banana', text: "banana rage fuel" },
          { icon: 'Apple', text: "apple anything NOW" },
          { icon: 'Fish', text: "emergency sushi" },
          { icon: 'Salad', text: "NOT salad, ever" },
          { icon: 'Egg', text: "egg battle rations" },
          { icon: 'Nut', text: "nuts or YOUR nuts" },
          { icon: 'Carrot', text: "cake or consequences" },
          { icon: 'Cookie', text: "cookie countdown" },
          { icon: 'IceCream', text: "frozen fury food" }
        ]
      }
    },
    ui: {
      tabs: {
        mood: 'Status',
        calendar: 'Danger Calendar',
        history: 'Survival Log',
        settings: 'Settings'
      },
      buttons: {
        save: 'Save Settings',
        cancel: 'Abort Mission',
        markPeriod: 'Code Red Alert',
        export: 'Export Intel',
        import: 'Import History'
      },
      labels: {
        cycleLength: 'Mission Duration',
        startDate: 'Last Incident Date',
        notifications: 'Warning System',
        testMode: 'Simulation Mode'
      }
    }
  }
};

// Helper functions
const phraseTracking = {
  queen: {},
  king: {}
};

export const getRandomPhrase = (mode, phase, type) => {
  const key = `${mode}_${phase}_${type}`;
  
  if (!phraseTracking[mode]) {
    phraseTracking[mode] = {};
  }
  
  if (!phraseTracking[mode][key]) {
    phraseTracking[mode][key] = {
      used: [],
      lastIndex: -1
    };
  }
  
  const tracking = phraseTracking[mode][key];
  const phrases = modeContent[mode].phases[phase][type];
  
  // If all phrases have been used, reset
  if (tracking.used.length >= phrases.length) {
    tracking.used = [];
  }
  
  // Find unused phrases
  const availableIndices = phrases
    .map((_, index) => index)
    .filter(index => !tracking.used.includes(index));
  
  // Pick a random unused phrase
  const randomIndex = availableIndices[Math.floor(Math.random() * availableIndices.length)];
  tracking.used.push(randomIndex);
  tracking.lastIndex = randomIndex;
  
  return phrases[randomIndex];
};

export const resetPhraseTracking = (mode) => {
  if (mode) {
    phraseTracking[mode] = {};
  } else {
    phraseTracking.queen = {};
    phraseTracking.king = {};
  }
};

export const getUIText = (mode, category, key) => {
  return modeContent[mode]?.ui?.[category]?.[key] || '';
};